## Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
# For Open-PS2-Loader
## Thanks to:
# - izdubar@psx-scene and jimmikaelkael@psx-scene
#   <http://psx-scene.com/forums/f150/%5Blinux%5D-opl-compile-guides-63749/>
# - Bat Rastard@psx-scene and doctorxyz@psx-scene
#   <http://psx-scene.com/forums/f150/2015-linux-mint-vm-creation-opl-compiling-guide-ps2sdk-127047/index3.html#post1169435>
# - and a lot of people around internet :)

dist: trusty
sudo: required
language: c
cache: ccache

## Fix make_changelog.sh
git:
  depth: 9999999

before_install:
  ## Save env dir
  - cd ../
  - export TRAVIS_ENV_DIR=$(pwd)

  ## Save repo name
  - export NEW_REPO_SLUG=$(echo ${TRAVIS_REPO_SLUG} | cut -f 1 -d "/")

  ## Make CCache good to us
  - export PATH="/usr/lib/ccache:${PATH}"

install:
  ## Dependencies
  - sudo apt-get install -yqqq gcc-4.4 patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev ccache libmpc-dev

before_script:
  ## Make cleanup, just for prevent anything
  - rm -rf ${TRAVIS_ENV_DIR}/gsKit/ ${TRAVIS_ENV_DIR}/ps2toolchain/ ${TRAVIS_ENV_DIR}/ps2-packer/ ${TRAVIS_ENV_DIR}/ps2sdk-ports/

  ## Set up the environment
  - export PS2DEV=${TRAVIS_ENV_DIR}/ps2dev
  - export PS2SDK=${PS2DEV}/ps2sdk
  - export PATH=${PATH}:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
  - export GSKIT=${PS2DEV}/gsKit
  - export LANG=C
  - export LC_ALL=C

  ## Clone all dependencies
  - git clone --quiet https://github.com/ps2dev/ps2toolchain.git ${TRAVIS_ENV_DIR}/ps2toolchain/
  - git clone --quiet https://github.com/sp193/ps2sdk-ports.git ${TRAVIS_ENV_DIR}/ps2sdk-ports/
  - git clone --quiet https://github.com/ps2dev/gsKit.git ${TRAVIS_ENV_DIR}/gsKit/
  - git clone --quiet https://github.com/ps2dev/ps2-packer.git ${TRAVIS_ENV_DIR}/ps2-packer/
  - chmod +x $(find . -name \*sh)

  ## PS2Toolchain
  - cd ${TRAVIS_ENV_DIR}/ps2toolchain/
  - travis_wait 60 bash ./toolchain.sh > /tmp/OPNPS2LD-PS2TOOLCHAIN.log 2>&1
  - curl --upload-file /tmp/OPNPS2LD-PS2TOOLCHAIN.log https://transfer.sh/OPNPS2LD-PS2TOOLCHAIN-${NEW_REPO_SLUG}-NIGHTLY${TRAVIS_BUILD_NUMBER}.log

  ## Build dependencies need for OPL
  - for TARGET in "ps2sdk-ports/zlib" "ps2sdk-ports/libpng"
    "ps2sdk-ports/libjpeg" "ps2sdk-ports/freetype2" "gsKit" "ps2-packer"; do
    cd ${TRAVIS_ENV_DIR}/${TARGET}/; make; make install; done

script:
  ## Go back to opl dir
  - cd ${TRAVIS_BUILD_DIR}/

  ## BUG: If we not call './make_changelog.sh' before 'make', it will always
  ## build OPL with old REVISION, and make things confuse
  ##
  ## Make a new changelog
  - bash ./make_changelog.sh

  ## Hack to prevent '-dirty' flag
  - git add -A

  ## Let's build Open PS2 Loader Release!
  - make release LOCALVERSION=${NEW_REPO_SLUG}

  ## Make the lang pack
  - bash ./lng_pack.sh

after_success:
  ## Upload the build
  - export OPL_VERSION=$(make oplversion)
  - curl --upload-file ${TRAVIS_BUILD_DIR}/OPNPS2LD-${OPL_VERSION}-${NEW_REPO_SLUG}.ZIP https://transfer.sh/OPNPS2LD-${OPL_VERSION}-${NEW_REPO_SLUG}-NIGHTLY${TRAVIS_BUILD_NUMBER}.zip
  - curl --upload-file ${TRAVIS_BUILD_DIR}/OPNPS2LD_LANGS-${OPL_VERSION}.zip https://transfer.sh/OPNPS2LD_LANGS-${OPL_VERSION}-NIGHTLY${TRAVIS_BUILD_NUMBER}.zip

