## Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
# For Open-PS2-Loader
## Thanks to:
# - izdubar@psx-scene and jimmikaelkael@psx-scene
#   <http://psx-scene.com/forums/f150/%5Blinux%5D-opl-compile-guides-63749/>
# - Bat Rastard@psx-scene and doctorxyz@psx-scene
#   <http://psx-scene.com/forums/f150/2015-linux-mint-vm-creation-opl-compiling-guide-ps2sdk-127047/index3.html#post1169435>
# - and a lot of people around internet :)
sudo: required
language: c

services:
  - docker

before_install:
## Save current dir, go to previous dir and save it too
- export opl_build_dir=$(pwd)
- cd ../
- export travis_build_dir=$(pwd)

before_script:
## Make cleanup, just for prevent anything
- cd ${travis_build_dir}/
- rm -rf gsKit/ ps2eth/ ps2-packer/ ps2sdk-ports/

## Set up the environment.
- export PS2ETH=${PS2DEV}/ps2eth
- export GSKIT=${PS2DEV}/gsKit
- export LANG=C
- export LC_ALL=C

## ps2dev/PS2SDKPorts
- cd ${travis_build_dir}/
- git clone --quiet https://github.com/ps2dev/ps2sdk-ports.git ${travis_build_dir}/ps2sdk-ports/

## ps2dev/PS2SDKPorts/zlib
- cd ${travis_build_dir}/ps2sdk-ports/zlib/
- make
- make install

## ps2dev/PS2SDKPorts/libpng
- cd ${travis_build_dir}/ps2sdk-ports/libpng/
- make
- make install

## ps2dev/PS2SDKPorts/libjpeg
- cd ${travis_build_dir}/ps2sdk-ports/libjpeg/
- make
- make install

## ps2dev/PS2SDKPorts/freetype
- cd ${travis_build_dir}/ps2sdk-ports/freetype-2.4.12/
- source SetupPS2.sh

## ps2dev/PS2ETH
- cd ${travis_build_dir}/
- git clone --quiet https://github.com/ps2dev/ps2eth ${travis_build_dir}/ps2eth/
- cd ${travis_build_dir}/ps2eth/
- make
- sudo mkdir -p /usr/lib/ps2dev/ps2eth
- sudo tar c $(find . -name \*irx) | sudo tar x -C /usr/lib/ps2dev/ps2eth

## ps2dev/gsKit
- cd ${travis_build_dir}/
- git clone --quiet https://github.com/ps2dev/gsKit.git ${travis_build_dir}/gsKit/
- cd ${travis_build_dir}/gsKit/
- make
- make install

## ps2dev/PS2Packer
- cd ${travis_build_dir}/
- git clone --quiet https://github.com/ps2dev/ps2-packer.git ${travis_build_dir}/ps2-packer/
- cd ${travis_build_dir}/ps2-packer/
- make
- make install

script:
## Let's build Open PS2 Loader Release!
- docker run -it --rm -v ${opl_build_dir}/ mlafeldt/ps2dev make

## Build Lang Pack and Latest Changelog
- docker run -it --rm -v ${opl_build_dir}/ mlafeldt/ps2dev ./lng_pack.sh

## [TEMPLATE] Deploy OPL to Github Releases
# 1. Clone this repository
# 2. Copy '.travis.yml' to '.travis-original.yml' (you will need it after)
# 3. Install Travis Client <https://github.com/travis-ci/travis.rb#installation>
# 4. Run command: $(travis setup releases)
#    After follow all previous steps, pickup ONLY the "secure" line
#    and change it on '.travis-original.yml'
# 5. Move '.travis-original.yml' to '.travis.yml'
# 6. Commit it
## NOTE: You need to configure TravisCI before anything <https://travis-ci.org/>

## Deploy OPL to Github Releases
deploy:
  provider: releases
  skip_cleanup: true
#  api_key:
#    secure: [PUT YOUR NEW SECURE API KEY HERE]
  file_glob: true
  file:
    - "${opl_build_dir}/OPNPS2LD-*.zip"
    - "${opl_build_dir}/OPNPS2LD_LANGS-*.zip"
  on:
    tags: true
